SELECT
    SM.SKU_CODE,
    SM.SKU_NAME,
    ICCAT.ICCAT_CODE,
    ICCAT.ICCAT_NAME,
    WH.WH_CODE,
    WL.WL_CODE,
    SUM(SKM.SKM_QTY) AS SUM_QTY,
    UQ.UTQ_NAME AS UNIT_NAME

FROM
    dbo.SKUMASTER SM
    INNER JOIN dbo.ICCAT ON SM.SKU_ICCAT = ICCAT.ICCAT_KEY
    INNER JOIN dbo.ICDEPT ON SM.SKU_ICDEPT = ICDEPT.ICDEPT_KEY
    INNER JOIN dbo.BRAND ON SM.SKU_BRN = BRAND.BRN_KEY
    INNER JOIN dbo.UOFQTY UQ ON SM.SKU_S_UTQ = UQ.UTQ_KEY
    INNER JOIN dbo.SKUMOVE SKM ON SM.SKU_KEY = SKM.SKM_SKU
    INNER JOIN dbo.WARELOCATION WL ON SKM.SKM_WL = WL.WL_KEY
    INNER JOIN dbo.WAREHOUSE WH ON WL.WL_WH = WH.WH_KEY
    INNER JOIN dbo.DOCINFO ON SKM.SKM_DI = DOCINFO.DI_KEY
    INNER JOIN dbo.DOCTYPE ON DOCINFO.DI_DT = DOCTYPE.DT_KEY
GROUP BY
    SM.SKU_CODE,
    SM.SKU_NAME,
    ICCAT.ICCAT_CODE,
    ICCAT.ICCAT_NAME,
    WH.WH_CODE,
    WL.WL_CODE,
    UQ.UTQ_NAME
HAVING
    SUM(SKM.SKM_QTY) > 0
ORDER BY
    SM.SKU_CODE,
    ICCAT.ICCAT_CODE,
    WH.WH_CODE,
    WL.WL_CODE